[project]
name = "storia-real-estate-pipeline-gcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "google-cloud-bigquery>=3.42.2",
    "google-cloud-storage>=3.10.0",
    "h2>=4.3.0",
    "httpx>=0.28.1",
    "lxml>=6.0.2",
    "pyarrow>=24.0.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.1",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["."]
testpaths = ["tests"]
